/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffClientsRouteImport } from './routes/staff/clients'
import { Route as StaffCommandRouteImport } from './routes/staff/command'
import { Route as StaffConnectionsRouteImport } from './routes/staff/connections'
import { Route as StaffConsoleRouteImport } from './routes/staff/console'
import { Route as StaffInboxRouteImport } from './routes/staff/inbox'
import { Route as StaffOperationsRouteImport } from './routes/staff/operations'
import { Route as StaffPayrollRouteImport } from './routes/staff/payroll'
import { Route as StaffProductsRouteImport } from './routes/staff/products'
import { Route as StaffPromptRouteImport } from './routes/staff/prompt'
import { Route as StaffProtocolRouteImport } from './routes/staff/protocol'
import { Route as StaffQrRouteImport } from './routes/staff/qr'
import { Route as StaffReportRouteImport } from './routes/staff/report'
import { Route as StaffVaultRouteImport } from './routes/staff/vault'
import { Route as StaffVerifyRouteImport } from './routes/staff/verify'
import { Route as StaffWarrantyRouteImport } from './routes/staff/warranty'
import { Route as StaffWorkforceRouteImport } from './routes/staff/workforce'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClientsRoute = StaffClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => StaffRoute,
} as any)
const StaffCommandRoute = StaffCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConnectionsRoute = StaffConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConsoleRoute = StaffConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInboxRoute = StaffInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOperationsRoute = StaffOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPayrollRoute = StaffPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProductsRoute = StaffProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPromptRoute = StaffPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProtocolRoute = StaffProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => StaffRoute,
} as any)
const StaffQrRoute = StaffQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => StaffRoute,
} as any)
const StaffReportRoute = StaffReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVaultRoute = StaffVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVerifyRoute = StaffVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWarrantyRoute = StaffWarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWorkforceRoute = StaffWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => StaffRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
