/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffInboxRouteImport } from './routes/staff/inbox'
import { Route as StaffOperationsRouteImport } from './routes/staff/operations'
import { Route as StaffProductsRouteImport } from './routes/staff/products'
import { Route as StaffPromptRouteImport } from './routes/staff/prompt'
import { Route as StaffProtocolRouteImport } from './routes/staff/protocol'
import { Route as StaffVerifyRouteImport } from './routes/staff/verify'
import { Route as StaffWorkforceRouteImport } from './routes/staff/workforce'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const StaffInboxRoute = StaffInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => StaffRoute,
} as any)
const StaffOperationsRoute = StaffOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProductsRoute = StaffProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPromptRoute = StaffPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProtocolRoute = StaffProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => StaffRoute,
} as any)
const StaffVerifyRoute = StaffVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => StaffRoute,
} as any)
const StaffWorkforceRoute = StaffWorkforceRouteImport.update({
  id: '/workforce',
  path: '/workforce',
  getParentRoute: () => StaffRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assurance': typeof AssuranceRoute
  '/careers': typeof CareersRoute
  '/login': typeof LoginRoute
  '/solutions': typeof SolutionsRoute
  '/staff': typeof StaffRouteWithChildren
  '/verify': typeof VerifyRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/prompt': typeof StaffPromptRoute
  '/staff/protocol': typeof StaffProtocolRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/workforce': typeof StaffWorkforceRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assurance': typeof AssuranceRoute
  '/careers': typeof CareersRoute
  '/login': typeof LoginRoute
  '/solutions': typeof SolutionsRoute
  '/verify': typeof VerifyRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/prompt': typeof StaffPromptRoute
  '/staff/protocol': typeof StaffProtocolRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/workforce': typeof StaffWorkforceRoute
  '/staff': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRoute
  '/assurance': typeof AssuranceRoute
  '/careers': typeof CareersRoute
  '/login': typeof LoginRoute
  '/solutions': typeof SolutionsRoute
  '/staff': typeof StaffRouteWithChildren
  '/verify': typeof VerifyRoute
  '/staff/inbox': typeof StaffInboxRoute
  '/staff/operations': typeof StaffOperationsRoute
  '/staff/products': typeof StaffProductsRoute
  '/staff/prompt': typeof StaffPromptRoute
  '/staff/protocol': typeof StaffProtocolRoute
  '/staff/verify': typeof StaffVerifyRoute
  '/staff/workforce': typeof StaffWorkforceRoute
  '/staff/': typeof StaffIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/assurance'
    | '/careers'
    | '/login'
    | '/solutions'
    | '/staff'
    | '/verify'
    | '/staff/inbox'
    | '/staff/operations'
    | '/staff/products'
    | '/staff/prompt'
    | '/staff/protocol'
    | '/staff/verify'
    | '/staff/workforce'
    | '/staff/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analysis'
    | '/assurance'
    | '/careers'
    | '/login'
    | '/solutions'
    | '/verify'
    | '/staff/inbox'
    | '/staff/operations'
    | '/staff/products'
    | '/staff/prompt'
    | '/staff/protocol'
    | '/staff/verify'
    | '/staff/workforce'
    | '/staff'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/assurance'
    | '/careers'
    | '/login'
    | '/solutions'
    | '/staff'
    | '/verify'
    | '/staff/inbox'
    | '/staff/operations'
    | '/staff/products'
    | '/staff/prompt'
    | '/staff/protocol'
    | '/staff/verify'
    | '/staff/workforce'
    | '/staff/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRoute
  AssuranceRoute: typeof AssuranceRoute
  CareersRoute: typeof CareersRoute
  LoginRoute: typeof LoginRoute
  SolutionsRoute: typeof SolutionsRoute
  StaffRoute: typeof StaffRouteWithChildren
  VerifyRoute: typeof VerifyRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/inbox': {
      id: '/staff/inbox'
      path: '/inbox'
      fullPath: '/staff/inbox'
      preLoaderRoute: typeof StaffInboxRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/operations': {
      id: '/staff/operations'
      path: '/operations'
      fullPath: '/staff/operations'
      preLoaderRoute: typeof StaffOperationsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/products': {
      id: '/staff/products'
      path: '/products'
      fullPath: '/staff/products'
      preLoaderRoute: typeof StaffProductsRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/prompt': {
      id: '/staff/prompt'
      path: '/prompt'
      fullPath: '/staff/prompt'
      preLoaderRoute: typeof StaffPromptRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/protocol': {
      id: '/staff/protocol'
      path: '/protocol'
      fullPath: '/staff/protocol'
      preLoaderRoute: typeof StaffProtocolRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/verify': {
      id: '/staff/verify'
      path: '/verify'
      fullPath: '/staff/verify'
      preLoaderRoute: typeof StaffVerifyRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/workforce': {
      id: '/staff/workforce'
      path: '/workforce'
      fullPath: '/staff/workforce'
      preLoaderRoute: typeof StaffWorkforceRouteImport
      parentRoute: typeof StaffRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StaffRouteChildren {
  StaffInboxRoute: typeof StaffInboxRoute
  StaffOperationsRoute: typeof StaffOperationsRoute
  StaffProductsRoute: typeof StaffProductsRoute
  StaffPromptRoute: typeof StaffPromptRoute
  StaffProtocolRoute: typeof StaffProtocolRoute
  StaffVerifyRoute: typeof StaffVerifyRoute
  StaffWorkforceRoute: typeof StaffWorkforceRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffInboxRoute: StaffInboxRoute,
  StaffOperationsRoute: StaffOperationsRoute,
  StaffProductsRoute: StaffProductsRoute,
  StaffPromptRoute: StaffPromptRoute,
  StaffProtocolRoute: StaffProtocolRoute,
  StaffVerifyRoute: StaffVerifyRoute,
  StaffWorkforceRoute: StaffWorkforceRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRoute,
  AssuranceRoute: AssuranceRoute,
  CareersRoute: CareersRoute,
  LoginRoute: LoginRoute,
  SolutionsRoute: SolutionsRoute,
  StaffRoute: StaffRouteWithChildren,
  VerifyRoute: VerifyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
